### ISSUE TITLE
remove all references to Firefox OS on the new CD Participation Hub

### ISSUE THREAD

**Issue by MarciaZikan** [mozilla/feedthefox#222] opened 2016-04-07 13:33 UTC
@ppapadeas Please, remove all references to Firefox OS on the new CD Participation Hub

**Comment by brianking** [comment] 2016-04-26 09:34
Possible dupe of #219 or this is broader in scope.

**Comment by comzeradd** [comment] 2016-05-05 14:15
Do we just replace Firefox OS with Connected Devices or do we need to make any adjumests on the text? I'm mostly talking about the About text on the frontpage.

**Comment by MarciaZikan** [comment] 2016-05-05 16:15
@comzeradd Please, add this new copy About Connected Devices on the frontpage:

Welcome to the Connected Devices Participation Hub, your starting point to get involved in Connected Devices, both through our Product Innovation Process and our Community Experimentation Launchpad.
Join a vibrant open source community and make Connected Devices a platform for innovation that will unlock the power of the web.

Find out ways to get involved and stay tuned for more information soon !

**Comment by brianking** [comment] 2016-05-17 05:47
P1 - 20160517

**Closed as completed** 2022-01-20 15:13 UTC
Labels: ARCHIVED - http://mzl.la/ghe-archive
